version: '3'
services:
  iconrpcserver:
    image: 'iconloop/prep-node:1905292100xdd3e5a'
    container_name: 'prep-node'
    volumes:
      - ./data:/data
    ports:
      - 9000:9000
  loopchain:
    image: 'iconloop/prep-node:1905292100xdd3e5a'
    container_name: 'prep-node'
    volumes:
      - ./data:/data
    ports:
      - 7100:7100

  scoredb:
    image: icon/icon-score-postgres
    container_name: 'prep-node'
    volumes:
      - ./data:/data
    ports:
      - 5432:5432
  blockdb:
    image: icon/icon-score-mongodb
    container_name: 'prep-node'
    volumes:
      - ./data:/data
    ports:
      - 27017:27017
  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    ports:
      - 443:443
    depends_on:
      - container
