apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: loopchain
  name: loopchain
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: loopchain
    spec:
      containers:
      - image: iconloop/prep-node:1905292100xdd3e5a
        name: prep-node
        ports:
        - containerPort: 7100
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: loopchain-claim0
      restartPolicy: Always
      volumes:
      - name: loopchain-claim0
        persistentVolumeClaim:
          claimName: loopchain-claim0
status: {}
