version: '3'
services:
  container:
    image: 'iconloop/prep-node:1905292100xdd3e5a'
    container_name: 'prep-node'
    volumes:
      - ./data:/data
    ports:
      - 9000:9000
      - 7100:7100
  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    ports:
      - 443:443
    depends_on:
      - container
